from .news_plaginator import *
from .contacts import *
from .courses_list import *
from .doc_site import *
from .index import *
from .login import *
from .news import *
from .news_plaginator import *
from .news_detail import *
from .courses_detail import *
